CREATE TABLE FRANJA_HORARIA (
	CODIGO VARCHAR(10) PRIMARY KEY NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	HORA_INICIO TIMESTAMP NOT NULL, 
	HORA_FIN TIMESTAMP NOT NULL, 
	VALOR_POR_HORA DECIMAL(10, 2) NOT NULL, 
	OBSERVACIONES VARCHAR(100) NOT NULL, 
	HORAS_VALORES VARCHAR(100) NOT NULL
);
CREATE TABLE USUARIO (
	USERNAME VARCHAR(100) PRIMARY KEY NOT NULL, 
	CLAVE VARCHAR(2000) NOT NULL, 
	NOMBRE VARCHAR(100) NOT NULL, 
	TIPO VARCHAR(20) NOT NULL, 
	ESTADO VARCHAR(20) NOT NULL
);
CREATE TABLE ACTIVIDAD (
	CODIGO VARCHAR(100) PRIMARY KEY NOT NULL, 
	ENTRADA TIMESTAMP NOT NULL,  
	SALIDA TIMESTAMP NOT NULL,   
	VALOR DECIMAL(20, 2) NOT NULL,  
	VALOR_HORA_FRACCION DECIMAL(20, 2) NOT NULL,  
	TIPO_CLIENTE VARCHAR(20) NOT NULL, 
	OBSERVACIONES VARCHAR(1000) NOT NULL, 
	FRANJA_HORARIA VARCHAR(20) NOT NULL,  
	CANTIDAD_HORAS INT NOT NULL
);
