CREATE TABLE FRANJA_HORARIA (
	CODIGO VARCHAR(10) PRIMARY KEY NOT NULL, 
	NOMBRE VARCHAR(50) NOT NULL, 
	HORA_INICIO TIMESTAMP NOT NULL, 
	HORA_FIN TIMESTAMP NOT NULL, 
	VALOR_POR_HORA DECIMAL(10, 2) NOT NULL, 
	OBSERVACIONES VARCHAR(100) NOT NULL, 
	HORAS_VALORES VARCHAR(100) NOT NULL
);